### ISSUE TITLE
ArtworkProvider doesn't work properly for SoundCloud tracks

### ISSUE THREAD

**Issue by drac-dot-gay** [angelobreuer/Lavalink4NET#107]
**Describe the bug**
When attempting to resolve the artwork uri for a track off of soundcloud, ArtworkService currently throws a 404 exception.

**To Reproduce**
1. Setup artwork service
2. Feed it a track from soundcloud
3. Observe a 404 not found exception thrown

**Expected behavior**
The track artwork properly resolving

**Screenshots**
N/A

**(please complete the following information):**
 - 3.0.0-preview-11
 - Described above

**Additional context**
The fix for this is simple, according to soundcloud's [docs](https://developers.soundcloud.com/docs/oembed), the track url, not the identifier, needs to be provided. I can open a PR and submit the fix myself if necessary.

**Comment by angelobreuer** [comment]
Thank you! I would be happy if you would create a PR
