### ISSUE TITLE
Lavalink4NET.DiscordNet.GetChannelUsersAsync doesn't work

### ISSUE THREAD

**Issue by TheKrush** [angelobreuer/Lavalink4NET#111]
**Describe the bug**
This method always returns the total number of users on the server, not just the voice channel.
![image](https://user-images.githubusercontent.com/671500/204114590-295c7a7f-6ed7-4c61-bde4-6075106b8038.png)
In this example, I was alone in the channel with the bot. So the count should have been 1.

**To Reproduce**
1. Join a voice channel.
2. Make the bot start playing to join the channel.
3. Check the return value of the method.

**Expected behavior**
That this method only counts people currently in the voice channel excluding any bots.

**Screenshots**
![image](https://user-images.githubusercontent.com/671500/204114629-05e40b08-8b4b-4a0e-ba84-8bce4bb0a5ae.png)

**(please complete the following information):**
 - Lavalink4NET Version : 2.1.1

**Comment by TheKrush** [comment]
If the tracker becomes like this it seems to work:
```
            inactivityTrackingService.AddTracker(async (player, client) =>
            {
                if (player.VoiceChannelId is null)
                {
                    return true;
                }

                // count the users in the player voice channel (bot excluded)
                //var userCount = (await client.GetChannelUsersAsync(player.GuildId, player.VoiceChannelId.Value)).Where(s => s != client.CurrentUserId).Count();

                var channel = await _client.GetChannelAsync(player.VoiceChannelId.Value) as SocketVoiceChannel;
                var userCount = channel.ConnectedUsers.Count(user => !user.IsBot);

                return userCount == 0;
            });
```

_client is just my DiscordSocketClient (since the client passed in is just a wrapper and doesn't have access to the GetChannelUsers method)

**Comment by MrCakeSlayer** [comment]
Yeah, this broke due to a change in Discord.Net (v3.7.0 iirc) which changed how certain properties counted users for voice channels (Those that are connected and those which can view the channel). Apparently just didn't get updated in Lavalink4NET yet. Using the `ConnectedUsers` property is the correct way to count users who are currently in voice channels now instead of the base `Users` property.

You could make a PR to update this in Lavalink4NET though if you want. :)

**Comment by angelobreuer** [comment]
This was already fixed by https://github.com/angelobreuer/Lavalink4NET/pull/109, but we can expand it to ignore bot accounts

**Comment by TheKrush** [comment]
Oh that must not be released through NuGet yet.

**Comment by angelobreuer** [comment]
![image](https://user-images.githubusercontent.com/46497296/204126875-d0c74ddc-29b1-4c88-b940-fcfd23128d1d.png)

I decompiled the preview 13 package and it seems to be included. But this feature is not in the release channel of Lavalink4NET.

I will file a PR for adding the bot check

**Comment by angelobreuer** [comment]
Package will be published together with https://github.com/angelobreuer/Lavalink4NET/issues/110 when ready
