### ISSUE TITLE
[Bug?] TrackEnd fires multiple times at once. [Question] Using rest instead of websocket?

### ISSUE THREAD

**Issue by asteria121** [angelobreuer/Lavalink4NET#114]
```
        public CommandModule(IAudioService audioService, IServiceProvider services)
        {
            _audioService = audioService ?? throw new ArgumentNullException(nameof(audioService));
            services.GetRequiredService<InactivityTrackingService>().InactivePlayer += Program_InactivePlayer;
            _audioService.TrackEnd += _audioService_TrackEnd;
        }

        private async Task _audioService_TrackEnd(object sender, Lavalink4NET.Events.TrackEndEventArgs eventArgs)
        {
            Console.WriteLine("track end fired");
            if (eventArgs.Player.CurrentTrack != null | eventArgs.Player.CurrentTrack.Context != null)
            {
                TrackContext context = (TrackContext)eventArgs.Player.CurrentTrack.Context;
                await context.TextChannel.SendMessageAsync("track ended");
            }
        }
```
[Bug?]
This is my code. I added TrackEnd event and it should be fired once when one track has ended. But TrackEnd fires multiple times at once like below. It prints multiple times console and discord textchannel both. I used player context to save textchannel that commands have been used. Is it bug or problem with my code?

[Question]
Latest lavalink displays like this when I use Lavalink4NET. Other lavalink library works well with REST.

"Sending websocket commands to Lavalink has been deprecated and will be removed in API version 4. API version 3 will be removed in Lavalink 5. Please use the new REST endpoints instead."

Is there any method to use REST instead of websocket on Lavalink4NET? Thank you for your contribution.

![1](https://user-images.githubusercontent.com/24371508/213915373-1d6c8319-74ec-4eb5-9802-7c1589b317fa.png)

**Comment by angelobreuer** [comment]
Seems like Lavalink introduced the new REST API a few weeks ago (https://github.com/freyacodes/Lavalink/blob/master/IMPLEMENTATION.md). 

Unfortunately, Lavalink4NET currently does not support the new REST API. I will expect to be able to do the migration in a few days.

---

The problem with Lavalink firing the event multiple times is a problem well known if you use transient instances with singleton instances together. The audio service is an instance that is always the same during the entire runtime of the bot. Each time a command is executed a new instance of the command module is created for the execution of the command. Following this, each time the constructor is called, which then registers the event one more time. So the more you execute commands, the more often the events are fired! You should only subscribe to the event once (for example when your bot starts), or better: use a custom player for such tasks like channel agnostic players (which you seem to want to implement).

**Comment by tree8069** [comment]
Very fast feedback!! I made Initialize function to add event and call it on bot starts. Works perfectly that I intended.

And I have one more question.. Is there any method to use SendMessage on textchannel when InactivePlayer fired? This can't use currentTrack.Context so I can't send message like other event.

**Comment by asteria121** [comment]
> Seems like Lavalink introduced the new REST API a few weeks ago (https://github.com/freyacodes/Lavalink/blob/master/IMPLEMENTATION.md).
> 
> Unfortunately, Lavalink4NET currently does not support the new REST API. I will expect to be able to do the migration in a few days.
> 
> The problem with Lavalink firing the event multiple times is a problem well known if you use transient instances with singleton instances together. The audio service is an instance that is always the same during the entire runtime of the bot. Each time a command is executed a new instance of the command module is created for the execution of the command. Following this, each time the constructor is called, which then registers the event one more time. So the more you execute commands, the more often the events are fired! You should only subscribe to the event once (for example when your bot starts), or better: use a custom player for such tasks like channel agnostic players (which you seem to want to implement).

Very fast feedback!! I made Initialize function to add event and call it on bot starts. Works perfectly that I intended.

And I have one more question.. Is there any method to use SendMessage on textchannel when InactivePlayer fired? This can't use currentTrack.Context so I can't send message like other event.

**Comment by angelobreuer** [comment]
You can probably access the player of the inactive player event. Then you can access the `eventArgs (from inactive event).Player.CurrentTrack.Context`. The problem is that if the track ends, then the current track will be null.

I would recommend you to use a custom player type where you can track the text channel. The track context is attached to the lifetime of the track instance. It would make more sense to attach the information you need (the text channel here) to the player.

You can inherit a class from the player type you want (e.g., QueuedLavalinkPlayer) and adjust the corresponding player factory (used by the JoinAsync method to create the player). There you can also override a method which is invoked when a track ends, so you do not even need the event subscription anymore.

**Comment by asteria121** [comment]
> You can probably access the player of the inactive player event. Then you can access the `eventArgs (from inactive event).Player.CurrentTrack.Context`. The problem is that if the track ends, then the current track will be null.
> 
> I would recommend you to use a custom player type where you can track the text channel. The track context is attached to the lifetime of the track instance. It would make more sense to attach the information you need (the text channel here) to the player.
> 
> You can inherit a class from the player type you want (e.g., QueuedLavalinkPlayer) and adjust the corresponding player factory (used by the JoinAsync method to create the player). There you can also override a method which is invoked when a track ends, so you do not even need the event subscription anymore.

I appreciate you! Plz enjoy my cup of coffe.
