### ISSUE TITLE
REST API Support

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#118]
**Is your feature request related to a problem? Please describe.**
Seems like Lavalink now have a new REST API. 
![image](https://github.com/angelobreuer/Lavalink4NET/assets/29896317/1792971a-0262-4fec-949a-ee84656b6642)
![image](https://github.com/angelobreuer/Lavalink4NET/assets/29896317/0a016c41-6bf7-4a1f-91a3-32cdd5d23250)

May be it worth to implement it?

**Comment by angelobreuer** [comment]
Rest API implementation is currently tracked by #117. It will be released together with the v4 release of Lavalink itself (which is not released yet).

**Comment by SKProCH** [comment]
Is there is any changelist for lavalink v4?

**Comment by angelobreuer** [comment]
Lavalink v4 itself does not really have any features or regressions of features. The majority of changes are infrastructure changes.
Lavalink4NET in constrast will have a lot of changes of how players are maintained, how tracks are enqueued. Before publishing Lavalink**4NET** v4 I will provide a change log.

**Comment by angelobreuer** [comment]
You can find the documented changes there: https://github.com/lavalink-devs/Lavalink/blob/master/CHANGELOG.md

**Comment by SKProCH** [comment]
Lavalink 4 preview was released, btw: https://github.com/lavalink-devs/Lavalink/discussions/904

**Comment by angelobreuer** [comment]
A first **_alpha_** version (v4.0.0-alpha.1) is now available, for interested users who want to try out Lavalink4NET v4. The PR contains a list of changes, the migration guide will follow

**Comment by SKProCH** [comment]
Yeah, I know. Don't think, I'm not calling to run and do something, I just saw that there is a new release and decided to write here, in case it will be useful for you.

**Comment by angelobreuer** [comment]
Yes, thank you. In my above comment, I was talking about the Lavalink4NET release (not the Lavalink server) that implements these features and just wanted to emphasize that Lavalink**4NET** v4 released its first alpha release but users should be very careful with using it. I just want to provide a first release, for users wanting to experiment, and maybe get a first feedback

**Comment by angelobreuer** [comment]
Lavalink4NET v4 beta is now available 🚀

**Comment by SKProCH** [comment]
Hello. Firstly, thanks!

Is there a guides/changelog/something to help with migration?

**Comment by angelobreuer** [comment]
A guide for the migration not yet, but will be added to the docs in 1-2 days. The documentation for v4 is already available at https://lavalink4net.angelobreuer.de/docs/category/introduction .

**Comment by angelobreuer** [comment]
@SKProCH You can find the migration guide [here](https://lavalink4net.angelobreuer.de/docs/migration/V4%20Guide). The list may not be comprehensive, feel free to ask here, in discussions, on the Lavalink4NET Support discord (preferred), or some else communication method you can think of (don't take that too literally).

**Comment by SKProCH** [comment]
@angelobreuer thanks, you are really doing the wonderful job!
