### ISSUE TITLE
LavalinkNode does not recover from an unexpected websocket terminaison

### ISSUE THREAD

**Issue by hmathieu31** [angelobreuer/Lavalink4NET#134]
**Describe the bug**
After the LavalinkNode has connected to the Lavalink websocket server, if the connection is interrupted (typically because the process running the Lavalink server has been killed), LavalinkNode is stuck in an infinite exception loop from which it seems to me it cannot recover.

Aside from the fact it can't recover from this exception even if the Lavalink server were to come back online, the behaviour is a `while (true)` logging loop without delay which can produce a considerable amount of logs.

**To Reproduce**
1. Start Lavalink server
1. Setup a LavalinkPlayer and start the hosted service
2. Kill Lavalink server
3. This exception gets logged infinitely
```
2024-01-02 23:01:08.648 +01:00 [ERR] [Lavalink-0HN0BRN2E09BM] Exception occurred during communication.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at Lavalink4NET.Socket.LavalinkSocket.ReceiveAsync(CancellationToken cancellationToken) in /home/runner/work/Lavalink4NET/Lavalink4NET/src/Lavalink4NET/Socket/LavalinkSocket.cs:line 76
   at Lavalink4NET.LavalinkNode.ReceiveInternalAsync(ILavalinkSocket socket, CancellationToken cancellationToken) in /home/runner/work/Lavalink4NET/Lavalink4NET/src/Lavalink4NET/LavalinkNode.cs:line 495
```
4. Restart Lavalink server
5. The exception loop continues infinitely

**Expected behavior**
When the connection has been unexpectedly killed, the player should return back to the initial reconnection state and attempt reconnections to the server using the `ExponentialBackoffReconnectStrategy`.
This would both solve the logs explosion issue and allow for a reconnection when the server is back online.

**(please complete the following information):**
 - Lavalink4NET Version: 4.0.5
 - Exception thrown? (consider enabling logging) : The root exception is a `WebSocketException` with `ConnectionClosedPrematurely` `WebSocketErrorCode`. It is caught and logged by `LavalinkNode.ReceiveInternalAsync`

**Comment by angelobreuer** [comment]
Thank you for finding the issue and also fixing it. Your changes will be part of version 4.0.6.
