### ISSUE TITLE
Skipping track with an empty queue always adds a `TrackQueueItem` to the history, rather than the actual item that was played

### ISSUE THREAD

**Issue by NycroV** [angelobreuer/Lavalink4NET#141]
**Describe the bug**
Whenever `await player.SkipAsync()` is called, and there are no more tracks in the queue, a `TrackQueueItem` is added to the queue's history rather than the item that was actually playing. This does not occur if there are items in the queue - if there are items in the queue, and `await player.SkipAsync()` is called, the correct item that was just playing is added to the history.

**To Reproduce**
1. Create a custom implementation of `ITrackQueueItem`
2. Play an instance of this type - do not add any more tracks to the queue, only play it once
3. Call `await player.SkipAsync()`
4. Collect the most recent item in the `player.Queue.History`
5. See that no matter what type of item was played and skipped, a `TrackQueueItem` is always returned here

**Expected behavior**
The history should contain an instance of whatever type of item was played and skipped, rather than a `TrackQueueItem`.

**Screenshots**
![image](https://github.com/angelobreuer/Lavalink4NET/assets/83246959/1001aa71-b52f-48f4-ba97-851bda681ba0)
![image](https://github.com/angelobreuer/Lavalink4NET/assets/83246959/88f3993f-bfa9-48e4-b4bf-46c692e08fe0)

**(please complete the following information):**
 - Lavalink4NET Version: 4.0.8
 - Exception thrown: N/A

**Additional context**
In the snippet provided, `count` is 1.
As previously mentioned, having more items in the queue will add the correct item to the history. Below is the same code snippet as above, but executed with additional items in the queue.
![image](https://github.com/angelobreuer/Lavalink4NET/assets/83246959/43e819ba-4c0e-4264-ae23-03351e35487a)

**Comment by NycroV** [comment]
Played* 🤦‍♂️

**Comment by angelobreuer** [comment]
Hi @NycroV ,

I have pushed a possible release with a possible fix for this issue (4.1.0-beta.1). It more includes a general refactoring of the internal management of tracks which initially started by your issue.

**Comment by NycroV** [comment]
Awesome, thank you! I’ll be able to give it some testing in a short few hours, I’ll report back with results once I have them.

**Comment by NycroV** [comment]
Tested with the new beta build and the issue has been resolved. Thanks for the help!
