### ISSUE TITLE
When Lavalink4Net tries to resolve player on unavailable node it block all Discord.Net handling

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#173]
**Describe the bug**
It we add some node which not available (e.g. shutdowned), and bot tries to resolve player for it, Lavalink4Net will block all discord net event processing loop.

**To Reproduce**
1. Go to 'Lavalink4NET.Samples.Cluster'. No not change nodes addresses, since nodes should be unavailable anyway.
2. Provide token, launch
3. Try to execute play two times
4. After first try bot will stop the Discord.Net message processing

**Expected behavior**
It shouldn't block message processing.

**Screenshots**
![image](https://github.com/user-attachments/assets/47031c96-1a0b-466e-a775-360e36b797a1)  
![image](https://github.com/user-attachments/assets/63fcd141-b4a1-4cf7-b8bd-df3d7211468e)

**(please complete the following information):**
 - Lavalink4NET Version: 4.0.24
 - Exception thrown? Explicitly - none

**Additional context**
Lavalink tries to handle the voice connected event and send it to node, for which it will wait for node connection. But if the node is unavailable is will never happen.

**Comment by SKProCH** [comment]
Currently this PR will solve this problem, but i think what we should actually dispose player handle it connection unavailable for certain amount of time. But this is another PR, since currently i've don't have a time to implement it properly.

**Comment by angelobreuer** [comment]
Fixed by #174
