### ISSUE TITLE
Add DisposeOnDisconnect

### ISSUE THREAD

**Issue by FenikkusuNeko** [angelobreuer/Lavalink4NET#18]
Add a DisposeOnDisconnect bool in LavalinkNodeOptions (or another name).
Reason: As I can see if someone disconnects the bot through Discord (by having the permission) the player gets disposed and removed from the players dictionary.
But, I already made my own method to check if the bot was disconnected forcefully, so I can send a message in the music output channel. I can dispose the player then manually. But the event from the library gets triggered first before mine.
Can you add this option and some checks in your VoiceStateUpdated event?

**Comment by angelobreuer** [comment]
Okay, I've implemented the "PlayerDisconnected" and "PlayerConnected" which both hold the channel identifier connected to/disconnected from. The "PlayerDisconnected" also holds a cause which indicates the reason why the player disconnected (see possible causes: [PlayerDisconnectCause.cs](https://github.com/angelobreuer/Lavalink4NET/blob/f4de3f61a1906bef889f9f7385887b9cda1f3e14/src/Lavalink4NET/Events/PlayerDisconnectCause.cs)).

**Comment by FenikkusuNeko** [comment]
Awesome, I can't wait to try it.

**Comment by angelobreuer** [comment]
👌 Package (v1.4.6) is publishing 😊 Thanks!

PR: #19
