### ISSUE TITLE
Nodes stop trying to reconnect after reconnecting once

### ISSUE THREAD

**Issue by turulix** [angelobreuer/Lavalink4NET#22]
**Describe the bug**
A node stops trying to reconnect when it already reconnected once

**To Reproduce**
1. Start Lavalink
2. Connect to it using Lavalink4Net
3. Stop Lavalink
4. Start Lavalink
5. Stop Lavalink
6. Start Lavalink
7. See error

**Expected behavior**
A node should try to reconnect till it gets canceled via a event.

**Screenshots**

**(please complete the following information):**
 - Lavalink4NET Version
1.4.7
 - Exception thrown? (consider enabling logging)
No its caused by a logic misstake.

**Additional context**
Bug is caused by https://github.com/angelobreuer/Lavalink4NET/blob/56232d0aa84f94c922bfa3a0f8c8dce15b77796d/src/Lavalink4NET/LavalinkSocket.cs#L518-L522 being return not break

**Comment by angelobreuer** [comment]
Thanks for your report:

As you stated above I changed the `return` to a `break`; now the receive cycle continues after a reconnect:
https://github.com/angelobreuer/Lavalink4NET/blob/f216647f768426121a068b4605b83a61d86181a3/src/Lavalink4NET/LavalinkSocket.cs#L518-L522

(https://github.com/angelobreuer/Lavalink4NET/commit/f216647f768426121a068b4605b83a61d86181a3; [angelobreuer-patch-1](https://github.com/angelobreuer/Lavalink4NET/tree/angelobreuer-patch-1)).

I checked if the problem persists and now my client reconnects to the lavalink server once the connection is closed or aborted by the remote side (multiple tests).

You can download the build artifacts from the CI server: https://ci.appveyor.com/project/angelobreuer/lavalink4net/builds/31408139/artifacts

Please re-open the issue if the problem persists after the fix.
