### ISSUE TITLE
After disconnecting a node, it does not try to connect to it back sometimes

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#25]
**Describe the bug**
Sometimes after a node disconnects, it does not try to connect back to it. 

**To Reproduce**
1. Launch bot, connect to lavalink
2. While somebody uses lavalink in your bot, turn off the lavalink server

**Expected behavior**
I think that even if a node is disconnected while it is playing something, it is necessary to try to connect to it

 - Lavalink4NET Version 1.4.8

**Additional context**
According to my observations, this happens mainly when at that time the node reproduced something.

**Logs**
When node is free: 
```
(Stay-Online) Node died! Moving players to a new node...
Trying to resume Lavalink Session ... Key: xxx
```
When node are busy:
 ```
(Stay-Online) Node died! Moving players to a new node...
```

**Comment by angelobreuer** [comment]
Hello @SKProCH,
I tested the Stay-Online feature and it works as expected (see [Stay-Online](https://github.com/angelobreuer/Lavalink4NET/wiki/Stay-Online) documentation).

I just added some improvements, e.g. tracks continue at the position they stopped, fixed logic error, etc. (https://github.com/angelobreuer/Lavalink4NET/commit/91b42664128a6e9a3fe1fe5f85db4debbb27c711)

The stay-online feature moves players to a new node if a node disconnects.

Thanks in advance.

**Comment by SKProCH** [comment]
Yes, this fix my problem. But I also propose to improve the player a bit: Add an virtual method to the player that will be called when the player was dropped:
https://github.com/angelobreuer/Lavalink4NET/blob/91b42664128a6e9a3fe1fe5f85db4debbb27c711/src/Lavalink4NET/Cluster/LavalinkCluster.cs#L456-L457

**Comment by angelobreuer** [comment]
I've added a PlayerMoved event in LavalinkCluster which can be used to track dropped players:
https://github.com/angelobreuer/Lavalink4NET/blob/9ac591393218631182143ad1030eaf1674397720/src/Lavalink4NET/Cluster/LavalinkCluster.cs#L98-L101

If a player was dropped, the PlayerMovedEventArgs#TargetNode property is set to null and you can handle the dropped player.

Implementation for the event:
https://github.com/angelobreuer/Lavalink4NET/blob/9ac591393218631182143ad1030eaf1674397720/src/Lavalink4NET/Cluster/LavalinkCluster.cs#L467-L481

Event arguments structure:
https://github.com/angelobreuer/Lavalink4NET/blob/9ac591393218631182143ad1030eaf1674397720/src/Lavalink4NET/Events/PlayerMovedEventArgs.cs#L34-L53

**Comment by SKProCH** [comment]
Thanks. How soon will you be able to release a new version with these changes?

**Comment by angelobreuer** [comment]
I will start publishing the release now, it may take some time for validation, etc.
See CI status: https://ci.appveyor.com/project/angelobreuer/lavalink4net/builds/31585946

Thanks!
