### ISSUE TITLE
PlayerState.NotPlaying after server region change

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#27]
**Describe the bug**
The player state is reset to NotPlaying after the region at the server changes even if music was playing before

**To Reproduce**
1. Start bot
2. Start listening music
3. Change server region / wait for voice server auto change

**Expected behavior**
I think State should not change

 - Lavalink4NET v1.4.10

**Additional context**
I think this is the reason: https://github.com/angelobreuer/Lavalink4NET/blob/8ce6321da6352b536b2b3f00694b01f843a1a0d8/src/Lavalink4NET/Player/LavalinkPlayer.cs#L526

**Comment by angelobreuer** [comment]
Hello @SKProCH,

does the commit (https://github.com/angelobreuer/Lavalink4NET/commit/50d19393dfef3c410e82a09813297d5826dd98fc) fix your issue?

I corrected the statement: https://github.com/angelobreuer/Lavalink4NET/blob/50d19393dfef3c410e82a09813297d5826dd98fc/src/Lavalink4NET/Player/LavalinkPlayer.cs#L526-L529

Thanks in advance!

**Comment by SKProCH** [comment]
Yes, thanks
