### ISSUE TITLE
Processing bot moves through channels

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#28]
After the server administrator forces the bot to another voice channel, the bot is disconnected after some amount of time due to the inactivity tracker.

However, `VoiceChannelId` has a private setter and can only be changed using `ConnectAsync`. However, after calls to this method `State` is automatically set to `NotPlaying`, why is this done?

Maybe I'm doing something wrong or missing something?

**Comment by angelobreuer** [comment]
Hello @SKProCH,
thanks for your report!

In commit https://github.com/angelobreuer/Lavalink4NET/commit/7d519ec237d60273cb54842e1449c6873483365d I've added a check to ensure that the player state is only set to `PlayerState.NotPlaying` when the player is connected initially to the voice channel:
https://github.com/angelobreuer/Lavalink4NET/blob/7d519ec237d60273cb54842e1449c6873483365d/src/Lavalink4NET/Player/LavalinkPlayer.cs#L526-L531

Did this solve your issue?

You can try out the new artifacts from the CI build: https://ci.appveyor.com/project/angelobreuer/lavalink4net/builds/31979160/artifacts

Thanks in advance!

**Comment by SKProCH** [comment]
Yes, that solves my issue. When will this appear in the release?

**Comment by angelobreuer** [comment]
I am publishing the fix on NuGet and GitHub Tags now.

Thanks!
