### ISSUE TITLE
When restarting the bot and leaving Lavalink running it wont reconnect to the old player

### ISSUE THREAD

**Issue by NenoxAG** [angelobreuer/Lavalink4NET#30]
**Describe the bug**
When you try to leave Lavalink running (with a player running) and restart the bot, it won't reconnect to the player that is running rather create a new one. So the old player which is running cant be controlled anymore until it has a timeout.

**To Reproduce**
1. Start Lavalink
2. Start bot
3. Start music playback via Lavalink4NET
4. Stop bot
5. Start bot
6. Try to stop the playback, change volume, ...

**Expected behavior**
Lavalink4NET reconnects with the old player so that it can be used and controlled again.

 - Lavalink4NET 1.4.11

**Logs of Lavalink**

```

2020-04-09 14:37:08.197  INFO 30927 --- [   XNIO-1 I/O-8] lavalink.server.io.SocketServer          : Connection closed from /0:0:0:0:0:0:0:1:35214 with status CloseStatus[code=1006, reason=] -- Session can be resumed within the next 60 seconds with key xxx

2020-04-09 14:37:11.863  INFO 30927 --- [ XNIO-1 task-38] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /0:0:0:0:0:0:0:1:35236

2020-04-09 14:37:11.875  INFO 30927 --- [ XNIO-1 task-38] lavalink.server.io.SocketServer          : Connection successfully established from /0:0:0:0:0:0:0:1:35236

2020-04-09 14:37:11.883  INFO 30927 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op":"configureResuming","key":"yyy","timeout":60}

**Comment by angelobreuer** [comment]
Hello @NenoxAG,
thanks for your report!

If I understand you correctly, you want Lavalink4NET to resume players when you restart your bot infrastructure?

The Lavalink node does not inform the client about which players were playing before the connection aborted when reconnecting.

To resume the players when restarting the bot, we have to save or retrieve the information about what players were running when the bot crashed/was stopped.

The reconnect function is used only for connection aborts that happen on the networking level.
Bot or node crashes do not include resuming functionality.

Thanks in advance!

**Comment by NenoxAG** [comment]
Hey @angelobreuer,

yes you have understood me correctly. What I want is to be able to get the ResumeKey when a player starts and use the key when the bot restarted so it can resume to the connection and the audio controls like play, volume, ... work again.

Like mentioned here: https://github.com/Frederikam/Lavalink/blob/master/IMPLEMENTATION.md#resuming-lavalink-sessions

Thanks in advance!

**Comment by angelobreuer** [comment]
Hey @NenoxAG,

would it solve your issue, if we expose the `_resumeKey` field (see: [LavalinkSocket.cs#L58](https://github.com/angelobreuer/Lavalink4NET/blob/5ecdbc3916c23f0382f9eacc2ea53207604f41e5/src/Lavalink4NET/LavalinkSocket.cs#L58)) to a public-setter property?, e.g.:

```csharp
public string ResumeKey { get;  }
```

Thanks in advance!

**Comment by NenoxAG** [comment]
Yes that would solve the issue, thanks!
