### ISSUE TITLE
[Question] Player initialization

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#34]
I have a child class of the player that inherits from `LavalinkPlayer`.
Previously, the constructor passed `GuildId`, which was used in my player constructor to load guild information from the database. Now that the factory is being used, the constructor should be empty, but how do I know `GuildId` then?
When and how should I load guild information now?

**Comment by angelobreuer** [comment]
Hello @SKProCH,
thanks for your question.

```csharp
IAudioService node = [..];
IVoiceChannel voiceChannel = [..];

var myPlayer = await node.JoinAsync(() => new MyPlayer(voiceChannel.GuildId), voiceChannel.GuildId, voiceChannel.Id);
```

You can use the player factory to pass constructor parameters to your player implementation.
But there should be a better way to accomplish this, I will think about this later. Any help appreciated.

Thanks in advance!

**Comment by SKProCH** [comment]
Yes i get it, thanks
