### ISSUE TITLE
Moving player to new node

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#35]
**Describe the bug**
After the node falls, the player moves to another node. This is done through the 
https://github.com/angelobreuer/Lavalink4NET/blob/0dc3805ad7b415eeae2ba41ee0a2734803ccaf37/src/Lavalink4NET/LavalinkNode.cs#L661-L686
The player is first destroyed, and then the `UpdateAsync` method is called, which does not restore the state of the player from Destroyed
https://github.com/angelobreuer/Lavalink4NET/blob/0dc3805ad7b415eeae2ba41ee0a2734803ccaf37/src/Lavalink4NET/Player/LavalinkPlayer.cs#L549-L570
At the time this line was executed, the player is still destroyed:
https://github.com/angelobreuer/Lavalink4NET/blob/0dc3805ad7b415eeae2ba41ee0a2734803ccaf37/src/Lavalink4NET/Player/LavalinkPlayer.cs#L569
I think there should be something like:
```
     if (State == PlayerState.NotConnected || State == PlayerState.Destroyed) 
     { 
         State = PlayerState.NotPlaying; 
     } 
```

 - Lavalink4NET Version 1.4.14

**Comment by angelobreuer** [comment]
Hello @SKProCH,
thanks for your report!

I've added your suggested changes in https://github.com/angelobreuer/Lavalink4NET/commit/a7d2cda7caff16a82a0817e12baf265ae175d98b. Does this fix your issue?

You can try out the CI build artifacts: https://ci.appveyor.com/project/angelobreuer/lavalink4net/builds/32268362/artifacts

Thanks in advance!

**Comment by SKProCH** [comment]
Yes, thanks
