### ISSUE TITLE
Nodes personalization

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#37]
I think it would be useful to be able to give the node some parameters (e.g. name)

**Describe the solution you'd like**
I think this could be added to `LavalinkNodeOptions`

**Comment by angelobreuer** [comment]
Hello @SKProCH,
thanks for your suggestion!

I've added a new label configuration option in [`LavalinkNodeOptions`](https://github.com/angelobreuer/Lavalink4NET/blob/angelobreuer-patch-1/src/Lavalink4NET/LavalinkNodeOptions.cs):
https://github.com/angelobreuer/Lavalink4NET/blob/0a83ae0758eb333c29057ef7177f3c1223b7c604/src/Lavalink4NET/LavalinkNodeOptions.cs#L60-L66

The [`LavalinkNode`](https://github.com/angelobreuer/Lavalink4NET/blob/angelobreuer-patch-1/src/Lavalink4NET/LavalinkNode.cs) class has a new property [`Label`](https://github.com/angelobreuer/Lavalink4NET/blob/angelobreuer-patch-1/src/Lavalink4NET/LavalinkNode.cs#L128): https://github.com/angelobreuer/Lavalink4NET/blob/angelobreuer-patch-1/src/Lavalink4NET/LavalinkNode.cs#L128

I've also integrated the label property in the Cluster nodes which had a similar property (`Identifier`).

Does this solve your issue?

Thanks in advance!

**Comment by SKProCH** [comment]
Yes, thanks
