### ISSUE TITLE
An System.AggregateException occurred in VOICE_STATE_UPDATED.

### ISSUE THREAD

**Issue by LukeHallett** [angelobreuer/Lavalink4NET#39]
**Describe the bug**
When trying the play a track, I get an exception from 'VOICE_STATE_UPDATED'.

**Expected behavior**
Bot should play Music.

**Screenshots**
![3VgrOSOW](https://user-images.githubusercontent.com/32042040/80988292-33adfd80-8e2b-11ea-99fd-f4c709656f47.png)
![XC3TTjLW](https://user-images.githubusercontent.com/32042040/80988298-36a8ee00-8e2b-11ea-9e7c-d3f79d873338.png)

**(please complete the following information):**
 - Lavalink4NET Version: Latest

**Comment by angelobreuer** [comment]
Hello @LukeHallett,

you should first join the channel before you can retrieve the player for it.

If you want your bot to create a player for a voice channel, for example, use:
```csharp
[...]
// get the track information
var track = await Bot.AudioService.GetTrackAsync(song, SearchMode.YouTube);

// join the voice channel, and get the player
var player = await Bot.AudioService.JoinAsync(guild.Id, voice.Id);

// play the track
await player.PlayAsync((track);
[...]
```

Thanks in advance!

**Comment by LukeHallett** [comment]
I still get the same error with your example.

**Comment by angelobreuer** [comment]
Are you using the latest DSharpPlus version (, if not what version are you using)?

**Comment by LukeHallett** [comment]
I'm using 4.0.0-nightly-00688.

**Comment by angelobreuer** [comment]
There was an issue with accessing an internal property using reflection in the VoiceState.
Does the commit f94c959 fix your issue?
