### ISSUE TITLE
ArgumentNullException in inactivity tracking service

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#41]
**Describe the bug**
Global looped uncaught exception:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'player')
   at Lavalink4NET.Tracking.InactivityTrackingService.UntrackPlayerAsync(LavalinkPlayer player)
   at Lavalink4NET.Tracking.InactivityTrackingService.PollAsync()
```

**To Reproduce**
1. Setup inactivity tracking service
2. Use the bot
3. Wait (and when you're lucky)

**Expected behavior**
Probably when player = null you need to force remove it from the list or something

**(please complete the following information):**
 - Lavalink4NET Version 1.4.16

**Comment by angelobreuer** [comment]
Hello @SKProCH,
thanks for your bug report!

Does the commit bbfeede53832b5132dba8b9909c7293f40d0efbd fix your issue?

Thanks in advance!

**Comment by SKProCH** [comment]
I looked at the code, and yes, it should fix it. But, since the error appears from time to time and does not depend on anything (well, or I could not find because of what) it will be difficult to confirm this.

**Comment by angelobreuer** [comment]
I've pushed the release now (v.1.4.18, https://www.nuget.org/packages/Lavalink4NET/1.4.18) and we'll see if the issue persists.
Thanks in advance!

**Comment by SKProCH** [comment]
@angelobreuer everything seems to be fine. Could you make a new release of Lavalink4Net.Discord.Net (seems like pipelines failed)?
