### ISSUE TITLE
Getting the lyrics for a song

### ISSUE THREAD

**Issue by gam-dgb** [angelobreuer/Lavalink4NET#5]
Hello, I have the question, if it would be possible to put in, that you can retrieve the lyrics of a song using a method? I would need this feature for my Discord Bot.

I already have looked around for some API services and the best (free of course) I found is https://github.com/NTag/lyrics.ovh / https://lyrics.ovh.

**Comment by angelobreuer** [comment]
Nice idea! 👍 I've set that on the list for plans for next release version 1.2.0.

**Comment by angelobreuer** [comment]
Implementation complete. 🎉 The feature will be available in the next release version (1.2.0). If there are any further issues, please open a new issue.
