### ISSUE TITLE
QueuedLavalinkPlayer.State property incorrect after skip

### ISSUE THREAD

**Issue by 230Daniel** [angelobreuer/Lavalink4NET#51]
**Describe the bug**
The State property of QueuedLavalinkPlayer is set to NotPlaying after SkipAsync() is called.

**To Reproduce**
Steps to reproduce the behaviour:

1. Play a track by adding it to the queue using player.Queue.Add(track) and calling PlayTopAsync(track), where track has been dequeued.
![image](https://user-images.githubusercontent.com/49287178/92363843-09769000-f0ea-11ea-9533-2ef57fe73b06.png)

2. Add another track to the queue by using player.Queue.Add(track), but without calling PlayTopAsync() this time or dequeueing the track.

3. Skip to the next track using player.SkipAsync();

4. In a different method a bit later on, get the player using LavalinkNode.GetPlayer<QueuedLavalinkPlayer>() and check the State property. The player is playing music, the track finished event has not been called, and yet player.State is set to NotPlaying.

**Expected behaviour**
I would expect the player's state property to remain at playing and not change to NotPlaying.

**Screenshots**

![image](https://user-images.githubusercontent.com/49287178/92364812-881ffd00-f0eb-11ea-9eaf-a3998a64fc52.png)

**(please complete the following information):**
 - Lavalink4NET Version v1.4.21
 - Exception thrown: None

**Additional context**

In my case I'm finding that State is set to NotPlaying when I try to call my PlayPause method.
The player which has the incorrect value for State still has the correct values for the current track and position.
If I fetch the player immediately after calling SkipAsync(), State is still set to Playing.

**Comment by angelobreuer** [comment]
Hello @230Daniel,
I'm sorry, but I'm unable to reproduce your issue.

Can you show when the LavalinkPlayer sets its player state to `NonPlaying`? and/or the Lavalink logs? (to see if there are any corresponding events dispatched, Note to exclude any personal information, tokens, and passwords from the log)

___

Please note that the `LavalinkPlayer#PlayTopAsync` method appends the track to the **top** of the queue and plays the song if the player is not playing. You can use the `LavalinkPlayer#PlayAsync` method to achieve this: 

```csharp
int position = await player.PlayAsync(track);
Debug.Log(...);
```

instead of

```csharp
int position = player.Queue.Count;
player.Queue.Add(track);
Debug.Log(..);

if (currentTrack == null)
{
     // ..
}
```

Additionally, you do not have to keep track of the currently playing track (`CurrentTrack`) itself, you can retrieve it using the player (`player.CurrentTrack`).

___

I'm using the following code to reproduce your issue:

```csharp
// Play a track by adding it to the queue using player.Queue.Add(track) and
// calling PlayTopAsync(track), where track has been dequeued.
player.Queue.Add(track);
await player.PlayTopAsync(track);

Debug.Assert(player.State is PlayerState.Playing);
Debug.Assert(player.CurrentTrack is not null);

await Task.Delay(5000);

Debug.Assert(player.State is PlayerState.Playing);
Debug.Assert(player.CurrentTrack is not null);

// Add another track to the queue by using player.Queue.Add(track), but without
// calling PlayTopAsync() this time or dequeuing the track.
player.Queue.Add(track);

Debug.Assert(player.State is PlayerState.Playing);
Debug.Assert(player.CurrentTrack is not null);

var trackEndEventDispatched = false;
audioService.TrackEnd += async (_, _) => trackEndEventDispatched = true;

Debug.Assert(!trackEndEventDispatched);

// Skip to the next track using player.SkipAsync();
await player.SkipAsync();

// give the LavalinkNode some time to dispatch the TrackEndEvent
await Task.Delay(1000);

Debug.Assert(trackEndEventDispatched);

await Task.Delay(4000);

// In a different method a bit later on, get the player using
// LavalinkNode.GetPlayer() and check the State property. The player is playing
// music, the track finished event has not been called, and yet player.State is
// set to NotPlaying.
player = audioService.GetPlayer<QueuedLavalinkPlayer>(616986381373145099);

Debug.Assert(player.State is PlayerState.Playing); // ! Assertion should fail here according to the issue
Debug.Assert(player.CurrentTrack is not null);
```

The code above works fine __on my machine™__ in a single-guild environment with one channel.

___

The situations in which the player state is set to `NotPlaying` are...
- the player was forcefully disconnected from a voice channel.
- the player connected to another voice channel.
- a track ended (and no tracks are being enqueued in the case of the QueuedLavalinkPlayer)
- the player initially connected to a voice channel.

___

While researching I've got a catch where the problem might be, see the following code:

https://github.com/angelobreuer/Lavalink4NET/blob/7d8de3a5c4f2ccff0327d9663367a269c604fe0a/src/Lavalink4NET/Player/LavalinkPlayer.cs#L192-L205

Which is overridden by https://github.com/angelobreuer/Lavalink4NET/blob/7d8de3a5c4f2ccff0327d9663367a269c604fe0a/src/Lavalink4NET/Player/QueuedLavalinkPlayer.cs#L68-L76

and calls the base method. 

I've made a commit in which the state update is suppressed by the `QueuedLavalinkPlayer` could you please try out if your issue still persists in e2a371824414fc3bf174dadbed7c76bbe8110bda?

You can extract the following ZIP-file in your project build directory and run the project: [Lavalink4NET.dev-build-e2a371824414fc3bf174dadbed7c76bbe8110bda.zip](https://github.com/angelobreuer/Lavalink4NET/files/5183766/Lavalink4NET.dev-build-e2a371824414fc3bf174dadbed7c76bbe8110bda.zip).

___

Thanks in advance!

**Comment by 230Daniel** [comment]
Hi there, thank you for your very in-depth response!

I took a look at the commit and believe that it should fix the issue, but when trying to use the new files in that zip file I got some errors which I couldn't find a good solution to on google:

```
Unable to load one or more of the requested types.
Could not load file or assembly 'Lavalink4NET, Version=1.4.21.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Could not load file or assembly 'Lavalink4NET, Version=1.4.21.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Could not load file or assembly 'Lavalink4NET, Version=1.4.21.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Could not load file or assembly 'Lavalink4NET, Version=1.4.21.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Could not load file or assembly 'Lavalink4NET, Version=1.4.21.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Could not load file or assembly 'Lavalink4NET, Version=1.4.21.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```

I collected some more information for you too, here is a log file created by my console app which shows the status of the player every second. Lines labelled "Audio" are created when an event is fired by Lavalink4NET.
[log2.txt](https://github.com/angelobreuer/Lavalink4NET/files/5184031/log2.txt)


And here is the Lavalink log which I don't think shows anything going wrong.
[lavalog.txt](https://github.com/angelobreuer/Lavalink4NET/files/5184029/lavalog.txt)

Many thanks,
Daniel.

**Comment by angelobreuer** [comment]
Hello @230Daniel,
thanks for your response!

I've now managed to reproduce the issue! I applied the fix and the problem no longer appeared on my side. It seems like e2a371824414fc3bf174dadbed7c76bbe8110bda resolves the issue.

___

I have built the assemblies with a different package version which results in your error that the assembly's manifest does not match the referenced assembly. I rebuilt the assemblies with the correct version (v1.4.21):

[Lavalink4NET.dev-build-e2a371824414fc3bf174dadbed7c76bbe8110bda-v2.dbg.1.4.21.zip](https://github.com/angelobreuer/Lavalink4NET/files/5184437/Lavalink4NET.dev-build-e2a371824414fc3bf174dadbed7c76bbe8110bda-v2.dbg.1.4.21.zip)

___

Thanks in advance!
Angelo Breuer

**Comment by 230Daniel** [comment]
Hi, I still got the errors when using the new files. The error includes "1.4.21.0", so if you built using "1.4.21" then that could perhaps still be the problem?

Anyway, it's great to hear that you managed to reproduce the issue. Will you be creating a release on NuGet with this fix?

Many thanks, 
Daniel.

**Comment by angelobreuer** [comment]
Hey @230Daniel,
thanks again!

I've now rebuilt the packages again using the right Version (I've set the PackageVersion to 1.4.21, not the Version itself).
The version number 1.4.21 is equal to 1.4.21.0.

[Lavalink4NET.dev-build-e2a371824414fc3bf174dadbed7c76bbe8110bda-v3.dbg.1.4.21.zip](https://github.com/angelobreuer/Lavalink4NET/files/5184649/Lavalink4NET.dev-build-e2a371824414fc3bf174dadbed7c76bbe8110bda-v3.dbg.1.4.21.zip)

___

I am currently migrating Lavalink4NET to C# 8.0 (e.g. nullable context, etc.). Once I am done, I will push a new release (1.5.0) with the fix.

Thanks in advance!
Angelo Breuer

**Comment by angelobreuer** [comment]
I have now published the latest build to NuGet in which your issue should be fixed (1.5.0).

https://www.nuget.org/packages/Lavalink4NET/
https://www.nuget.org/packages/Lavalink4NET.Discord.NET/

Please re-open the issue if your problem still persists.

Thanks in advance!
Angelo Breuer

**Comment by 230Daniel** [comment]
Hi, I hate to bring bad news but the issue is still present after updating to v1.5, seemingly in exactly the same way.

Perhaps the issue is something to do with the way I'm adding tracks to the queue, please could you send the code you used to reproduce the issue so that I could compare it to mine?

The issue also occurred when using the dev files you sent to me (which worked this time :D)

Thanks again,
Daniel

(I don't have permission to re-open this issue as I didn't close it myself)

**Comment by 230Daniel** [comment]
I was looking through the code and it appears that the fix is not in place in the current version on Github? I don't know if the version on Github is the current version on NuGet or not.

```
public override async Task OnTrackEndAsync(TrackEndEventArgs eventArgs)
        {
            if (eventArgs.MayStartNext)
            {
                await SkipAsync();
            }

            await base.OnTrackEndAsync(eventArgs);
        }
```

doesn't match what I saw in the commit you made earlier.

Did you forget to merge the patch-1 branch?
https://github.com/angelobreuer/Lavalink4NET/compare/patch-1

Many thanks,
Daniel

**Comment by angelobreuer** [comment]
Hello @230Daniel,

> Did you forget to merge the patch-1 branch?

thank you for pointing out that I just forgot to merge the patch-1 branch!

___

> Perhaps the issue is something to do with the way I'm adding tracks to the queue, please could you send the code you used to reproduce the issue so that I could compare it to mine?

I've made a repository that shows I've reproduced your issue, see: https://github.com/angelobreuer/Lavalink4NET.I51Repro

If I am using v1.5.0 (without the patch) then the following issue appears:
![image](https://user-images.githubusercontent.com/46497296/92501326-ab879c80-f1fe-11ea-9205-ede5bd56a804.png)

But when using the commit from patch-1 the player state is set correctly:
![image](https://user-images.githubusercontent.com/46497296/92501537-fef9ea80-f1fe-11ea-94c9-6908b330c12f.png)

___

> I don't know if the version on Github is the current version on NuGet or not.

The GitHub releases are currently outdated but the NuGet feed should be up-to-date built by the CI.

___

> The issue also occurred when using the dev files you sent to me (which worked this time :D)

Do you mean you were able to load the files or is the issue solved in the dev files?

___

Thank you very much!
Angelo Breuer

**Comment by 230Daniel** [comment]
Excellent!

I was concerned that the issue wasn't fixed after the patch, but if you've just forgotten to implement the fix then that explains it all.

> Do you mean you were able to load the files or is the issue solved in the dev files?

I was able to load the files, but the not playing issue remained.

Thank you,
Daniel

**Comment by angelobreuer** [comment]
> I was able to load the files, but the not playing issue remained.

The dev files should have fixed the issue (as the patch was included in the dev files but not in 1.5.0):
![image](https://user-images.githubusercontent.com/46497296/92507699-a713b180-f207-11ea-894a-189dc2ef818d.png)

___

Does the reproduction repository (https://github.com/angelobreuer/Lavalink4NET.I51Repro) match your issue? Or is there any step is missed in the reproduction?

___

Thank you!
Angelo Breuer

**Comment by 230Daniel** [comment]
Hm, that's a good point.

While comparing the repository and my own code, I noticed no differences in the way it interacts with the library.

My method for using the dev files was probably incorrect. I pasted them into my bin\Debug\netcoreapp3.1 folder and ran using visual studio. The program ran so I assumed I was using the dev files, but I must not have been because there isn't a difference between your code and mine.

I used `dotnet publish` to publish for windows and replaced the relevant files in the output. I got the same "Could not load file or assembly" errors, confirming that I was not using the dev version when running from visual studio.

I therefore assume that the issue is fixed in the dev version.

Thanks!
Daniel

**Comment by angelobreuer** [comment]
Hi @230Daniel,

could you please run the following two commands in your project folder and check if the issue still persists:

```cmd
dotnet remove package Lavalink4NET.Discord.Net
dotnet add package Lavalink4NET.Discord.Net -v 1.5.0-e2a371824414fc3bf174dadbed7c76bbe8110bda -s https://pkgs.dev.azure.com/angelo-breuer/Lavalink4NET/_packaging/Lavalink4NET/nuget/v3/index.json
```

Those will download the CI build that includes the patch.

___

Thanks in advance!
Angelo Breuer

**Comment by 230Daniel** [comment]
That worked!

My project ran fine and the issue is completely fixed.

Thank you for your continued hard work and patience on this :)

**Comment by angelobreuer** [comment]
Thank you very much for taking the time to solve the issue!

I will then publish a hotfix (1.5.1) this time including the fix itself.

Thank you!
Angelo Breuer

**Comment by 230Daniel** [comment]
Hi @angelobreuer 

I thought I'd let you know that although this fix is perfect for me, it could potentially cause some issues for others.
I noticed that after my player had actually finished playing tracks (either by StopAsync or by reaching the end of the queue) the player state remained at Playing.

Perhaps you should add a check to determine whether or not there are tracks in the player's queue, and if not then run the base method?

Daniel

**Comment by angelobreuer** [comment]
Hello @230Daniel,
thanks for this information!

I've now added the following to the reproduction:
https://github.com/angelobreuer/Lavalink4NET.I51Repro/blob/master/Program.cs#L101-L106

___

I've made a commit in which the player state is corrected for all methods (e.g. in the SkipAsync) method and added additional statements to null out the `CurrentTrack` property.

You can view the diff here if you want: https://github.com/angelobreuer/Lavalink4NET/compare/patch-2

___

Could you please try out if the issue still persists in c7517f26490a9115a42809e132ddc454bab25fa8?

You can use the following two commands to use the patched version:

```cmd
dotnet remove package Lavalink4NET.Discord.Net
dotnet add package Lavalink4NET.Discord.Net -v 1.5.1-c7517f26490a9115a42809e132ddc454bab25fa8 -s https://pkgs.dev.azure.com/angelo-breuer/Lavalink4NET/_packaging/Lavalink4NET/nuget/v3/index.json
```

___

Thanks a lot!
Angelo Breuer

**Comment by 230Daniel** [comment]
Brilliant!

I tested several actions using the dev package and it seems to be working perfectly. Looking at the commit, I can't spot any other functionality issues.

Thank you again, I'm having a great time using your library for my bots and really appreciate your work :)
