### ISSUE TITLE
LavalinkNode.TrackStuck event not dispatched

### ISSUE THREAD

**Issue by 230Daniel** [angelobreuer/Lavalink4NET#54]
Tracks appear to get stuck, but the LavalinkNode.TrackStuck event is not triggered.
I'm not sure if the event should be called or not when I think it should, so I'll describe how my track is getting stuck as well.

**To reproduce:**

1. Connect a QueuedLavalinkPlayer to a channel.

2. Leave it connected for a really long time. During this time, Discord reconnects will occur. I'm not sure if this fact is related to the problem.

      > I'm using Discord.NET v2.3.0-dev-20200904.2 which is the latest dev release. I'm using this release because it correctly implements discord re-connects instead of failing to re-establish connections. The console outputs "Resumed previous session" instead of "Failed to resume previous session".

3. Play a track. The TrackStarted event is called. Sometimes, the bot doesn't get that little green ring and it makes no sound. The player's TrackPosition property advances 1 second, but never past that. 

     > If this occurs, then the bot will consistently have this issue until it is disconnected and re-connected to the channel. While one bot is experiencing this problem, other instances of the same bot connected to the same Lavalink server may not experience this problem.

4. Wait for one minute. The track finishes with reason CleanUp, and the TrackStuck event was never fired. TrackException is also not fired.

     > On the several occasions I have seen this issue occur, the CleanUp event was never fired earlier than 1 minute and a few seconds after the track starts. The latest I've seen it fire was at one minute and 7 seconds after the TrackStarted event was called.

**Expected behaviour**
I believe that the TrackStuck event should fire because the player's TrackPosition property appears to remain constant. (I didn't test this thoroughly, the only output I have of this value is a value accurate to 1 second which is updated every 10 seconds).

**Details**

Lavalink4NET v1.5.2
Discord.NET v2.3.0-dev-20200904.2

Console output when this behaviour occurs:
```
14:50:37 | Debug | Search  | SearchResult for query songo di volare. (19 tracks)
14:50:37 | Debug | Player  | Added to queue in position 0: Christopher Tin - Sogno di Volare ("The Dream of Flight") (Civilization VI Main Theme)
14:50:37 | Debug | Audio   | Track started: Christopher Tin - Sogno di Volare ("The Dream of Flight") (Civilization VI Main Theme)
14:51:41 | Debug | Audio   | Track finished (CleanUp)
```

Lavalink server output when this behaviour occurs:
```
2020-09-20 14:50:36.617  INFO 24196 --- [lava-daemon-pool-info-loader-2-thread-24] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: songo di volare
2020-09-20 14:50:37.171  INFO 24196 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"play","guildId":"687018691023601726","track":"QAAAvwIAVkNocmlzdG9waGVyIFRpbiAtIFNvZ25vIGRpIFZvbGFyZSAoIlRoZSBEcmVhbSBvZiBGbGlnaHQiKSAoQ2l2aWxpemF0aW9uIFZJIE1haW4gVGhlbWUpAA9DaHJpc3RvcGhlciBUaW4AAAAAAAOlmAALV1FZTjJQM0UwNnMAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1XUVlOMlAzRTA2cwAHeW91dHViZQAAAAAAAAAA","startTime":0,"noReplace":false}
2020-09-20 14:50:37.172  INFO 24196 --- [lava-daemon-pool-playback-1-thread-5] c.s.l.e.y.tools.ip.Ipv6Block             : /hidden
2020-09-20 14:50:37.622  INFO 24196 --- [lava-daemon-pool-playback-1-thread-5] c.s.l.e.y.tools.ip.Ipv6Block             : /hidden
2020-09-20 14:56:39.330  INFO 24196 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"687018691023601726"}
```

Console output when a Discord re-connect occurs: (discord.net client output)
```
14:42:15 | Info  | Gateway | Disconnecting
14:42:15 | Info  | Gateway | Disconnected
14:42:16 | Info  | Gateway | Connecting
14:42:17 | Info  | Gateway | Resumed previous session
14:42:17 | Info  | Gateway | Connected
```

Similar behaviour also occurs for another person who is writing a music bot in JavaScript (erela.js I believe). They're using the same Lavalink server as me. This is why I'm making an issue about the TrackStuck event not being called, instead of the problem of the tracks themselves getting stuck.

Thank you in advance,
from Daniel.

**Comment by angelobreuer** [comment]
Hello @230Daniel,
thank you for your report!

The LavalinkNode simply redirects the incoming payload to events, as you can see here:
https://github.com/angelobreuer/Lavalink4NET/blob/30ff72bc6c1146f3c7f2f74b1e1b52de8359fd64/src/Lavalink4NET/LavalinkNode.cs#L405-L445

Also, the LavalinkPlayer never dispatches the CleanUp track end reason itself.

I think your issue is related to the Lavalink Server itself and not with the library, as the behavior also occurs when the "another person" interacts with the Lavalink Server. So I think your issue belongs to here: https://github.com/Frederikam/Lavalink

Much thanks!
Angelo Breuer

**Comment by 230Daniel** [comment]
Oh right, it's definitely not an issue with this library then.

I thought that perhaps Lavalink4NET detected when a track got stuck like this and raised the event accordingly.

Thank you for the help!
Daniel
