### ISSUE TITLE
Add interface to LavalinkTrack 

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#55]
**Is your feature request related to a problem? Please describe.**
I am missing the ability to override the track implementation.

**Describe the solution you'd like**
It would be nice to have `ILavalinkTrack` or something similar. I also wanted to have a generic player implementation like `LavalinkPlayer<T>` `where T : ILavalinkTrack`

**Comment by angelobreuer** [comment]
Hello @SKProCH,

Can you provide a use case related to your feature request?

You should be able to inherit from the LavalinkTrack class (as it is not sealed) and pass it around the Lavalink methods:

https://github.com/angelobreuer/Lavalink4NET/blob/d9fb4a522169dc91a0642db8046e38a30de026a9/src/Lavalink4NET/Player/LavalinkTrack.cs#L37

Thanks in advance!
Angelo Breuer

**Comment by SKProCH** [comment]
I would like to create something like a container for other tracks with additional information, this is necessary to implement my ideas. Class inheritance in this case is not enough for me, I need to be able to change the implementation of track properties.

I think that adding `ILavalinkTrack` should not change the code for existing users.

**Comment by angelobreuer** [comment]
> Class inheritance in this case is not enough for me, I need to be able to change the implementation of track properties.

Do you mind if I make the properties of LavalinkTrack virtual, like in https://github.com/angelobreuer/Lavalink4NET/commit/277d7e52dc59afbd0b6fbabca3622ded8669affc#diff-69b736e4f12d2a869ec1f2f6aba46f62?

> I can describe my idea in its entirety, but it takes a long time and I don't think I can find a good other way.

I can imagine some reasons for that too.

> I think that adding ILavalinkTrack should not change the code for existing users.

Adding an interface would require a lot more than just using virtual members because all method signatures that refer to the LavalinkTrack class have to be updated, etc.

Thanks in advance!

**Comment by SKProCH** [comment]
Yes, in principle I can change my approach to be limited to virtual properties. Thanks

**Comment by angelobreuer** [comment]
Thanks! Should I merge https://github.com/angelobreuer/Lavalink4NET/commit/277d7e52dc59afbd0b6fbabca3622ded8669affc then and push out a minor release?

**Comment by SKProCH** [comment]
I think yes
