### ISSUE TITLE
Track null while moving player to another node

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#58]
**Describe the bug**
When we try to change the node for the player, we get an exception, because when the player is destroyed, the current track is nulled.

**To Reproduce**
1. Start playing something
2. Switch node
3. See error

 - Lavalink4NET Version 1.5.3
 - Exception thrown:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'track')
   at Lavalink4NET.Player.LavalinkPlayer.PlayAsync(LavalinkTrack track, Nullable`1 startTime, Nullable`1 endTime, Boolean noReplace)
   at Lavalink4NET.LavalinkNode.MovePlayerInternalAsync(LavalinkPlayer player, LavalinkNode node)
   at Lavalink4NET.LavalinkNode.MovePlayerAsync(LavalinkPlayer player, LavalinkNode node)
```

**Additional context**
CurrentTrack become null after this: https://github.com/angelobreuer/Lavalink4NET/blob/22aaa446ac69b6f054d63f493aa66d4cffeb3c84/src/Lavalink4NET/LavalinkNode.cs#L679

**Comment by angelobreuer** [comment]
Hello @SKProCH,
Thanks for reporting this issue!

Can you try out if your issue still persists in 53b1b7ea0fc1afc5679aafac24750cd46f7f38e3?
You can copy the following assemblies to your output/build directory to try out:

[Lavalink4NET.zip (1.5.3.0 Release angelobreuer-patch-1@53b1b7e)](https://github.com/angelobreuer/Lavalink4NET/files/5433027/Lavalink4NET.zip)

Many thanks,
Angelo Breuer

**Comment by SKProCH** [comment]
Yes, all working now. Thanks!
