### ISSUE TITLE
Volume resets after node change

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#60]
**Describe the bug**
When we change a node, the volume for the node is 1, and the player retains the previous volume (from the old node).

**To Reproduce**
1. Start playing
2. Change node
3. See wrong volume level

 - Lavalink4NET Version 1.5.4

In my player implementation i override `OnConnectedAsync` and call `SetVolumeAsync` but it does nothing because player volume level already set (but wrong):
https://github.com/angelobreuer/Lavalink4NET/blob/0a7d98b8608498a57265970d0cc16698aa6e9753/src/Lavalink4NET/Player/LavalinkPlayer.cs#L394

I think I need to add a parameter here:
```
public virtual async Task SetVolumeAsync(float volume = 1f, bool normalize = false, bool force = false)
```
And change the method accordingly.

Perhaps it is also worth doing something with Volume, but I don't know how to do this better (because if after changing the node you just call SetVolumeAsync (with volume = 1), then this will break the system for saving the volume level for me, for example).

**UDP**. Perhaps just after changing the node, you need to forcibly send volume change, respectively, with the player's Volume property.

**Comment by angelobreuer** [comment]
Hello @SKProCH,
Thanks for your issue report.

I think it would be good to send the state to the Lavalink node moved to, so if you move the node, the Lavalink4NET service sends the state (volume, current track, equalizer bands) to the new node. So users do not have to manually work-around this.

I will also add the force parameter as you suggested above to both `LavalinkPlayer#SetVolumeAsync` and `LavalinkPlayer#UpdateEqualizerAsync`.

You can see the changes here: https://github.com/angelobreuer/Lavalink4NET/compare/angelobreuer-patch-2.
Do the changes above resolve your issue?

Many thanks,
Angelo Breuer

**Comment by SKProCH** [comment]
Yes, this solves my problem. Many thanks!
