### ISSUE TITLE
Can not install Lavalink4NET.MemoryCache to .NET Framework 4.7.2 project.

### ISSUE THREAD

**Issue by mon1t0r** [angelobreuer/Lavalink4NET#65]
Hi, I decided to use your library for making music functions for my discord bot, but when I tried to add Lavalink4NET.MemoryCache package from NuGet to my .NET Framework 4..7.2 project it gives me an error like "package is not supported on this platform". I created new .NET Core App project and it worked with it, but I need my project on .NET Framework. Could you please help me, thanks.

**Comment by angelobreuer** [comment]
Hello @mon1t0r,

It seems there are some problems with System.Runtime.Caching and .NET Framework.
For example, you could try out the workaround as described in this comment: https://github.com/Azure/azure-functions-host/issues/4581#issuecomment-510630802

Or you can implement your own caching using the https://github.com/angelobreuer/Lavalink4NET/blob/master/src/Lavalink4NET/ILavalinkCache.cs interface.

Thank you!

**Comment by angelobreuer** [comment]
Closing due inactivity, please feel free to reopen the issue, if you have any questions (or anything else).
