### ISSUE TITLE
Wrong bands comparing in UpdateEqualizerAsync

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#66]
**Describe the bug**
UpdateEqualizerAsync is not working properly.
If i have old: (Band - 0, Gain - 0) and new: (Band - 0, Gain - 1), method does nothing, although he should.

**(please complete the following information):**
 - Lavalink4NET 1.6.1

**Comment by angelobreuer** [comment]
Hello @SKProCH,
Thank you for your issue report.

Could you try to set the `force` parameter to `true` and tell me if you can set a new equalizer?

**Comment by SKProCH** [comment]
Yes i can set a new equalizer when `force` = `true`

**Comment by angelobreuer** [comment]
Hello @SKProCH,
I've prepared a fix in https://github.com/angelobreuer/Lavalink4NET/commit/ca06f7233e6f02371bb56661002e589f56b1cf54.
Would the above-linked commit resolve your issue?

**Comment by SKProCH** [comment]
I think yes. Unfortunately, I can't check it now, but I reviewed the changes, I think everything will work.
