### ISSUE TITLE
Bot will disconnect from the voice channel even after setting DisconnectOnStop to false

### ISSUE THREAD

**Issue by TheRedLord69** [angelobreuer/Lavalink4NET#68]
**Describe the bug**
When I stop the player with `await player.StopAsync(false);`  its supposed set the DisconnectOnStop to be false but when browsing through the break point I noticed that after this line, DisconnectOnStop is being true.

**Expected behavior**
When I do `StopAsync(false);` the DisconnectOnStop bool supposed to be false

Lavalink4NET version - 1.6.2
![image](https://user-images.githubusercontent.com/74541524/106389990-df9e6c80-63ee-11eb-9de4-100cdb2f021d.png)
![image](https://user-images.githubusercontent.com/74541524/106390082-62272c00-63ef-11eb-902c-a3685bfc4ce6.png)

*Note: In the second picture you can see how the debugger already passed the line with the `StopAsync(false);` but the DisconnectOnStop at the bottom of the page is set to true and the same happens if I write `StopAsync(false);` or `StopAsync(disconnect: false);`

**Comment by angelobreuer** [comment]
Could you try out setting `DisconnectOnStop` in your node configuration to `false`?

https://github.com/angelobreuer/Lavalink4NET/blob/69bddd6580f51b945ed4cbf8a11e61b2b8448e54/src/Lavalink4NET/LavalinkNodeOptions.cs#L50-L58

e.g.,

```cs
var options = new LavalinkNodeOptions 
{
	DisconnectOnStop = false,
};
```

**Comment by TheRedLord69** [comment]
> Could you try out setting `DisconnectOnStop` in your node configuration to `false`?
> 
> https://github.com/angelobreuer/Lavalink4NET/blob/69bddd6580f51b945ed4cbf8a11e61b2b8448e54/src/Lavalink4NET/LavalinkNodeOptions.cs#L50-L58
> 
> e.g.,
> 
> ```cs
> var options = new LavalinkNodeOptions 
> {
> 	DisconnectOnStop = false,
> };
> ```

Thank you very much ! you helped me a lot.
I was already lost and didnt knew what to do, searched every solution and tried anything I could think of :)
your solution worked !
