### ISSUE TITLE
GetTracksAsync query issue 

### ISSUE THREAD

**Issue by Dmitriy-ksm** [angelobreuer/Lavalink4NET#69]
When you set a GetTrack query with several parameters, lavalink receives an invalid GET request.

1. Create a new LavalinkNode;
2. Call the GetTracksAsync function for LavalinkNode with the following query https://www.youtube.com/watch?v=videoId&list=listId (for example: https://www.youtube.com/watch?v=7CMyNJXaJmU&list=RD7CMyNJXaJmU&start_radio=1&t=0);
3. This will create the following request /loadtracks?identifier=https://www.youtube.com/watch?v=videoId&list=listId
and it will be parsed as {identifier = https: //www.youtube.com/watch?v=videoId, list = listId} and will return only 1 track, not the whole mix.

The identifier parameter must be https: //www.youtube.com/watch?v=videoId&list=listId.

 - Lavalink4NET Version 1.6.2

I think it's worth to encode the request passed to GetTracks Async. At least it helped me.

**Comment by angelobreuer** [comment]
Thanks, @Dmitriy-ksm, for your issue report!
I could reproduce the issue and was able to fix it, as you suggested, by encoding the URI component.
This issue will be resolved in the next patch version.
