### ISSUE TITLE
DSharpPlus 5.0.0-nightly-00840 no longer exists

### ISSUE THREAD

**Issue by Silverdimond** [angelobreuer/Lavalink4NET#75]
According to the DSharpPlus discord server `- 5.0.0-nightly builds were pulled from SlimGet.`
[![image](https://user-images.githubusercontent.com/46320280/116830879-a4a60380-abac-11eb-8bd4-311d321bd6f1.png)](https://canary.discord.com/channels/379378609942560770/379386730538860554/837352800370556970)
That means [Line 20 in Lavalink4NET/src/Lavalink4NET.DSharpPlus/Lavalink4NET.DSharpPlus.csproj](https://github.com/angelobreuer/Lavalink4NET/blob/b28124d84d0deedf4d1028e7980c383db2f03d1d/src/Lavalink4NET.DSharpPlus/Lavalink4NET.DSharpPlus.csproj#L20) needs to be changed.

**Comment by angelobreuer** [comment]
Thank you @Silverdimond for the information!
I have pushed a new release (1.7.2) that uses the latest available nightly version.
