### ISSUE TITLE
Equalizer effect wrong name

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#78]
As I can see there is an error in the spelling of Name, which, as far as I can tell, makes it impossible to use the equalizer. (unfortunately I can't check for sure now)
https://github.com/angelobreuer/Lavalink4NET/blob/99ad00554c3c1f2cfb8a964c9fbd33944bdc2fae/src/Lavalink4NET/Filters/EqualizerFilterOptions.cs#L37

**Comment by angelobreuer** [comment]
Thank you! Should be fixed by #79 now (So that's the reason that I did not hear a difference while testing).
