### ISSUE TITLE
[Question] Custom tracks?

### ISSUE THREAD

**Issue by MrCakeSlayer** [angelobreuer/Lavalink4NET#82]
**Is your feature request related to a problem? Please describe.**
Hello, I recently swapped over to lavalink4net from Victoria due to scaling issues and have had zero issues so far. However, I was trying to look into doing a custom track to tack on additional info for the tracks however I don't see an easy way to do this nor do I see anything in the documentation for this. I was able to quickly and easily create a custom player and that works great, however I also have tracks-specific properties I need to implement.

**Describe the solution you'd like**
I'd like to be able to extend the tracks and use them in a custom player that I already have. Use case would be to show track requester info, source (as I support other sources like vlare, SoundCloud, direct web, etc), and some other misc stuff like dashboard-link IDs. If this is already possible, an example in the documentation would be nice as well for other users.

**Describe alternatives you've considered**
I could create a custom list of tracks in the custom player and use the tracks as a key, however this is a hacky solution compared to just being able to extend the existing tracks.

**Additional context**
Another side question I have: is there a public Discord server for lavalink4net where users can discuss and ask questions relating to lavalink4net? If so, could I get an invite to it?

**Comment by angelobreuer** [comment]
Hello @MrCakeSlayer,

this would be very a great thing to have in Lavalink4NET. Thank you!

I have therefore three solutions that would come to my mind for implementing the abovementioned:

Additional property on the `LavalinkTrack` class:
```cs
public object? Context { get; set; }
```
(additional names considered: "Data", "AdditionalInformation")

Advantages: Very lightweight, no breaking changes.
Disadvantage: Additional allocation per track, need to assign the context each time a track is requested.

After you requested a track from the lavalink node, you could do the following:

```cs
var track = await audioService.GetTrackAsync("<youtube search query>", SearchMode.YouTube);
var player = await audioService.JoinAsync<LavalinkPlayer>(BotCredentials.GuildId, BotCredentials.VoiceChannelId);

track.Context = new MyCustomTrackContext
{
    Requester = commandContext.User,
    TimeRequested = DateTimeOffset.UtcNow,
    // ...
};

await player.PlayAsync(track);

// Somewhere in code afterwards
var currentPlayer = player;
var myContext = (MyCustomTrackContext)currentPlayer.CurrentTrack.Context;
await SendMessageAsync($"The current track was requested by {myContext.Requester.Username}.");
```

There would be at least two more other possibilities to implement this (WeakReferenceTable or custom track creation method), but they would introduce breaking changes and would be more complex to implement for the user itself.

Would this fit your needs?

I've prepared an proposal, see https://github.com/angelobreuer/Lavalink4NET/commit/0e48875d7b3985822eafefb08009f1f240b307d0

---

I also created a Lavalink4NET support server which I also added to the README, here's a link:
[![Lavalink4NET Support Server Banner](https://discordapp.com/api/guilds/894533462428635146/embed.png?style=banner3)](https://discord.gg/cD4qTmnqRg)

**Comment by MrCakeSlayer** [comment]
Yes, this change would be sufficient for my needs and the fact that it doesn't introduce breaking changes is an added bonus. Appreciate the quick response! :)

**Comment by codyspeck** [comment]
@angelobreuer I'm wondering if there is a feature that exists today that satisfies the original poster's requirement. I'm running into a similar issue today where I would like to add some context to the track, like the text channel the end user requested the song be played in. I'm noticing though that the current `LavalinkTrack` class does not include the proposed `Context` property.

**Comment by MrCakeSlayer** [comment]
If you are talking about in regards to V4, it was removed, you can see a note about it in the migration guide here: <https://lavalink4net.angelobreuer.de/docs/migration/V4%20Guide#associating-data-with-tracks>

To do this in V4 you can make use of custom players. Reference to the docs here: <https://lavalink4net.angelobreuer.de/docs/custom-players/passing-data>

This example shows how you can store player-specific data like a text channel. however, if you also need per-track specific data you could take a look at some of the examples below:

With some **partial** code examples here:
```cs
public sealed record class TrackData(TrackReference Reference) : ITrackQueueItem
{
	public string Author;

	public int DashboardId;

	public Provider Provider;

	public SocketGuildUser Requester;

	public string Title;
}
```
Custom player (Note additional code is required for custom players, this is a very barebones partial example)
```cs
public sealed class CustomPlayer : QueuedLavalinkPlayer, IInactivityPlayerListener
{
public new TrackData? CurrentItem => (TrackData?)base.CurrentItem;
}
```
Setting track data
```cs
TrackData data = new TrackData(new TrackReference(trackItem))
{
	Requester = user,
	Provider = source,
	Author = overrideAuthor,
	Title = overrideAuthor + " - " + overrideTitle
};
```
Accessing data:
```cs
	player.CurrentItem?.Provider == Provider.Spotify
```

and just a final reminder this is intended as a partial example to show how it can be done and is not intended to just be blindly copied & pasted.

**Comment by angelobreuer** [comment]
@codyspeck I think that MrCakeSlayer already covered the most aspects.

In v4, we want to make the LavalinkTrack type more immutable which also meant that the `Context` property has been replaced  by another solution. You can now extend the entire `ITrackQueueItem` and only implement the properties needed for L4N to function. In your custom `ITrackQueueItem` you can then add as many properties as you like, including any information about the track request. When using the `QueuedLavalinkPlayer`, you can then "play" your `ITrackQueueItem` and access it by using the `QueuedLavalinkPlayer#CurrentItem` property. As MrCakeSlayer mentioned, it is recommended to add a custom property to your custom player, if you have one, to easily access the context data.

If you need any more information, don't hesitate to tell.

**Comment by MrCakeSlayer** [comment]
@codyspeck out of curiosity, did this end up working for you?

**Comment by codyspeck** [comment]
> @codyspeck out of curiosity, did this end up working for you?

Apologies for being quite late to respond to this. This absolutely did help me, thank you very much! This appears to work fine for the feature I'm implementing.

It does make me wonder if there's a race condition in accessing the `CurrentItem` property of the player in say a `TrackStarted` event where we may not end up actually grabbing the appropriate track, as I'm assuming the player passed into the event arguments is a stateful object. Regardless, and at a minimum, it seems it would be trivial to add a condition to at least verify the tracks are the same via comparing the titles or some other means.
