### ISSUE TITLE
Could Not Install Package 

### ISSUE THREAD

**Issue by Angshu1** [angelobreuer/Lavalink4NET#9]
so yeah i couldn't install tried everything.... maybe
any help would be appreciated

**Comment by angelobreuer** [comment]
Hello, I would like to have more information about your problem. 

What prevents you from installing the package? Are you using the NuGet-Package or using the DLL-File in the releases section? Is there any error message?

**Comment by Angshu1** [comment]
Ah Nevermind i fixed it but in other way.....

**Comment by angelobreuer** [comment]
Okay .. If you have any further problems (with the library), please open another issue.
