### ISSUE TITLE
Support for lavalink plugins

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#93]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to support third-party plugins for lavalink. For example - https://github.com/Topis-Lavalink-Plugins/Sponsorblock-Plugin

**Describe the solution you'd like**
Since plugins add their own events to transfer, it would be nice to be able to process all the events, extracting the necessary data from them. It would also be nice if we could also create libraries to support certain plugins.

**Additional context**
All lavalink plugins - https://github.com/topics/lavalink-plugin
Examples of events - [one](https://github.com/Topis-Lavalink-Plugins/Sponsorblock-Plugin/blob/master/src/main/java/com/github/topisenpai/plugin/sponsorblock/SponsorBlockPlugin.java#L128), [two](https://github.com/Topis-Lavalink-Plugins/Sponsorblock-Plugin/blob/master/src/main/java/com/github/topisenpai/plugin/sponsorblock/SegmentHandler.java#L33)
Also, It is also possible appearance of plugins that will not only send events, but also receive any non-standard messages. Perhaps we should consider supporting this.

**Comment by angelobreuer** [comment]
Thank you! I did not know that Lavalink supports plugins. I will work on it

**Comment by angelobreuer** [comment]
There are at the current time of writing five plugins listed in the PLUGINS.md of Lavalink:

- Google Cloud TTS

I also implemented this plugin, but Google Cloud TTS is a paid service and I do not have existing access to the Google Cloud APIs, so it is hard to test.

- SponsorBlock

Implemented, see above.

- Topis Source Manager

This plugin does not need client support.

- DuncteBot plugin

This plugin does not need client support.

- Extra Filter Plugin

Is this worth implementing? It does only support one additional echo filter.

**Comment by angelobreuer** [comment]
3.0.0-preview.1 includes alpha support for the SponsorBlock extension using the `Lavalink4NET.Integrations.SponsorBlock` NuGet package.

To initialize the integration, call the `UseSponsorBlock` method on the audio service:

![image](https://user-images.githubusercontent.com/46497296/175920342-3755105f-0adf-4cd6-95fa-e2de7b8df3ab.png)

You can configure the default categories to skip like:

![image](https://user-images.githubusercontent.com/46497296/175920558-30024b81-0f36-44ac-a819-1d928b538d2e.png)

You can also configure sponsorblock on a per-guild basis, like:

![image](https://user-images.githubusercontent.com/46497296/175920811-22556fe7-aa75-4077-8c66-94dabcd60b60.png)

Could you try out, if this fits your needs?

Thanks in advance!

**Comment by angelobreuer** [comment]
Linking commits

Integration API added: https://github.com/angelobreuer/Lavalink4NET/commit/eef740604712232155e4808bbfa20eb5424ec1c2
SponsorBlock API added: https://github.com/angelobreuer/Lavalink4NET/commit/35d0f65e903c2428e695ef8ae6da8048a9b97ac8

**Comment by angelobreuer** [comment]
@mrcakeslayer was kind enough to provide Google Cloud credentials to test the Google Cloud TTS integration, so now there is also support for text-to-speech:

![image](https://user-images.githubusercontent.com/46497296/176148169-0f75a829-c5d2-444b-94b2-9b6700f255b9.png)

![image](https://user-images.githubusercontent.com/46497296/176148070-ecf53863-d54a-45a3-b639-23f535bd62ae.png)

Linking commits:

Text To Speech Integration API added: https://github.com/angelobreuer/Lavalink4NET/commit/fd2ace9b88c588590dfb986871cdbdf30ff6aab6

**Comment by SKProCH** [comment]
Everything seems to be working fine.  
I can't check it in the release version of my bot yet (cuz i use my own fork with my changes), but it seems to work in the test app.  
I want to thank you very much for the support and development of this beautiful library.
