### ISSUE TITLE
Allow extending LavalinkClusterNode

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#94]
*After recent changes, it became difficult to update my fork library (because a big difference between the codebase has accumulated) and I want to port some of my changes to upstream, which would give up using the fork.*

**Is your feature request related to a problem? Please describe.**
In my bot i need to perform a custom actions when bot is kicked from the channel. Yes, it can be done in the global discordnet handler, but I need to change the behavior of the library when receiving an event from discord.

**Describe the solution you'd like**
- Make LavalinkClusterNode non sealed and allow overriding VoiceStateUpdated. 
- Allow creating user defined node implementations in LavalinkCluster (may be via factory defined at LavalinkClusterOptions) 

**Additional context**
May be good idea is a create generic LavalinkCluster for using with a user node implementations.  
My implementation [here](https://gitlab.com/enlivenbot/Lavalink4NET/-/commit/0b3cabf5831ea71560ba8df4a353af179dc794e8) (its not perfect, but worked for me)

**Comment by angelobreuer** [comment]
Closed by https://github.com/angelobreuer/Lavalink4NET/pull/100
