### ISSUE TITLE
Allow retrieving info about player' cluster

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#95]
*After recent changes, it became difficult to update my fork library (because a big difference between the codebase has accumulated) and I want to port some of my changes to upstream, which would give up using the fork.*

**Is your feature request related to a problem? Please describe.**
In my bot i need to display info about current node in player UI. 

**Describe the solution you'd like**
- Make LavalinkPlayer.LavalinkSocket getter public
- Add OnSocketChanged method to LavalinkPlayer to allow running custom actions when socket has changed

**Additional context**
[Here](https://gitlab.com/enlivenbot/Lavalink4NET/-/commit/326386fbab44b0353a0f4bcc23f0c22a15dfabfc) is implementation

**Comment by SKProCH** [comment]
Also, if you want, i can make it as a Pull Request

**Comment by angelobreuer** [comment]
Thank you! I looked at the implementation at it looks good. 

I have a only one thing to note:
- Please use file-scoped namespaces in SocketChangedEventArgs.cs

If you want you can make a pull request

**Comment by SKProCH** [comment]
Oh, thanks. I think I can create a PR during this week (hopefully tomorrow or the day after tomorrow)
