### ISSUE TITLE
Allow to store additional info along with track

### ISSUE THREAD

**Issue by SKProCH** [angelobreuer/Lavalink4NET#96]
*After recent changes, it became difficult to update my fork library (because a big difference between the codebase has accumulated) and I want to port some of my changes to upstream, which would give up using the fork.*

**Is your feature request related to a problem? Please describe.**
I need to store additional info along with track. Also this info can has different type, etc.   
For example is this the user, who requested track.

**Describe the solution you'd like**
- Add `ILavalinkTrackAttribute` empty marker interfact
- Add `public Dictionary<Type, ILavalinkTrackAttribute> Attributes { get; private set; }` to `LavalinkTrack`
- Add a couple helpers for this:
```csharp
/// <summary>
/// Add or update attribute
/// </summary>
/// <param name="requesterTrackAttribute">Target</param>
/// <param name="replace">If true existent attribute will be replaced</param>
/// <typeparam name="T">Attribute type</typeparam>
public void AddAttribute<T>(T requesterTrackAttribute, bool replace = true) where T : ILavalinkTrackAttribute{
    if (replace || !TryGetAttribute<T>(out _)) {
        Attributes[typeof(T)] = requesterTrackAttribute;
    }
}
/// <summary>
/// Get track attribute
/// </summary>
/// <param name="attribute">Out attribute</param>
/// <typeparam name="T">Attribute type</typeparam>
/// <returns>True if attribute exists</returns>
public bool TryGetAttribute<T>(out T attribute) where T : ILavalinkTrackAttribute {
    attribute = default!;
    if (!Attributes.TryGetValue(typeof(T), out var value)) return false;
    attribute = (T) value;
    return true;
}
/// <summary>
/// Get attribute if exists or create new one, add it and return
/// </summary>
/// <param name="factory">New attribute factory</param>
/// <typeparam name="T">Attribute type</typeparam>
/// <returns>Target attribute</returns>
public T GetOrAdd<T>(Func<T> factory) where T : ILavalinkTrackAttribute {
    if (TryGetAttribute(out T existentAttribute)) {
        return existentAttribute;
    }
    return (T) (Attributes[typeof(T)] = factory());
}
```

**Additional context**
[Here](https://gitlab.com/enlivenbot/Lavalink4NET/-/commit/2c5eecb55f032781c5a3c3408fb58eda11c5abc5) is my implementation  
I can also create a PR with this changes

**Comment by angelobreuer** [comment]
A while ago there was a similar request, I think the LavalinkTrack exposes a `Context` property for this issue

**Comment by SKProCH** [comment]
Hmm, yes, quite possibly, I must have missed it. Thank you.
